"""Knowledge base (P6): documents, retrievable chunks (pgvector + full-text), query log.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 18:57:12.458904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

EMBEDDING_DIM = 384
# PostgreSQL-only objects (not in the SQLAlchemy models; excluded from the drift test).
PG_UP = [
    "ALTER TABLE kb_chunks ADD COLUMN tsv tsvector GENERATED ALWAYS AS "
    "(to_tsvector('english', coalesce(heading, '') || ' ' || content)) STORED",
    "CREATE INDEX ix_kb_chunks_tsv ON kb_chunks USING gin (tsv)",
    "CREATE INDEX ix_kb_chunks_hnsw ON kb_chunks USING hnsw (embedding vector_cosine_ops)",
]

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _embedding_type():
    if _is_postgres():
        from pgvector.sqlalchemy import Vector

        return Vector(EMBEDDING_DIM)
    return sa.JSON()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('data_origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.create_index('ix_kb_documents_tenant', ['tenant_id', 'status'], unique=False)

    op.create_table('kb_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('embedding', _embedding_type(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['kb_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_kb_chunks_tenant_doc', ['tenant_id', 'document_id'], unique=False)

    op.create_table('kb_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('retrieval_mode', sa.String(length=32), nullable=False),
    sa.Column('results', sa.Integer(), nullable=False),
    sa.Column('top_score', sa.Double(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('cited_chunk_ids', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('supported_ratio', sa.Double(), nullable=True),
    sa.Column('latency_ms', sa.Double(), nullable=True),
    sa.Column('llm_call_id', sa.Integer(), nullable=True),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_queries', schema=None) as batch_op:
        batch_op.create_index('ix_kb_queries_tenant_created', ['tenant_id', 'created_at'], unique=False)

    if _is_postgres():
        for statement in PG_UP:
            op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    if _is_postgres():
        op.execute("DROP INDEX IF EXISTS ix_kb_chunks_hnsw")
        op.execute("DROP INDEX IF EXISTS ix_kb_chunks_tsv")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_queries', schema=None) as batch_op:
        batch_op.drop_index('ix_kb_queries_tenant_created')

    op.drop_table('kb_queries')
    with op.batch_alter_table('kb_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_kb_chunks_tenant_doc')

    op.drop_table('kb_chunks')
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_kb_documents_tenant')

    op.drop_table('kb_documents')
    # ### end Alembic commands ###
